In [7]:
#importation de la base et des packages
import pandas as pd
import numpy as np
import statsmodels.discrete.discrete_model as discrete_model
import re
from sklearn.linear_model import LinearRegression
df=pd.read_csv("C:/Users/sylva/OneDrive/Bureau/barometre/donnees_brutes_2021.csv", sep=";")

C:\Users\sylva\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (1,3,68,70) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [70]:
var_questions=[ 'Deplacement_a_pied', 'Agencement_voirie',
       'conflits_pietons', 'Conducteurs_respectent',
       'Circulation_vehicules_motorises', 'Deplacements_pied_commune',
       'Marche_securite', 'Securite_rues_services',
       'Securite_rues_residentielles', 'Securite_rejoindre_communes_voisines',
       'Acces_pietons', 'Marche_separe_circulation',
       'Marche_separe_autres_mobilites', 'Traverse_carrefour',
       'Deplacements_enfants_personnes_agees', 'Deplacements_enfants_ecole',
       'Pistes_cyclables', 'Espaces_pietons',
       'Espaces_pietons_libres_empietements', 'Espaces_pietons_entretenus',
       'Espaces_pietons_travaux', 'Signaletique_specifique',
       'Amenagements_confort_marcheurs', 'Troitoirs_eclaires',
       'Commune_ecoute_pietons', 'Commune_effort_marche', 'Situation_pietons',
       'Promotion_deplacement', 'Stationnement_espaces_pietons',
       'Acces_transport_commun', 'Signaletique', 'Information',
       'Resume_condition_marche']

In [11]:
df_questions=df[var_questions]
for i in var_questions:
    df_questions=df_questions[df_questions[i].notna()]

In [22]:

from sklearn.linear_model import LinearRegression
#données
x = np.array(df_questions[var_questions[1:]])
y = np.array(df_questions[var_questions[:1]])
#instancier modèle
model_linRegMul = LinearRegression()
#entrainement du modèle
model_linRegMul.fit(x, y)
#précision du modèle
precision = model_linRegMul.score(x, y)
print(precision*100)




67.99830585863972


In [26]:
inter=model_linRegMul.intercept_

In [35]:
coef=model_linRegMul.coef_
coef

array([[ 2.50255548e-01,  1.89282350e-02, -1.99528824e-02,
         6.64896363e-02,  2.10341969e-02,  1.89385402e-01,
         3.90011101e-02,  4.58604151e-02,  2.60137039e-03,
         1.34727558e-02,  1.07678533e-02,  6.76696106e-03,
        -2.32837687e-02,  2.27565643e-02,  1.54619921e-02,
        -1.76283164e-02,  3.98860953e-03, -2.80919563e-03,
         1.50434190e-02, -2.53072833e-02, -2.89800249e-04,
         2.74422847e-02, -3.61366772e-02,  1.11630480e-02,
        -1.29996549e-02,  8.94023847e-03,  1.38371474e-02,
        -2.09994803e-02, -2.65057425e-02,  1.61862842e-02,
        -5.77168452e-03,  3.31017893e-01]])

In [34]:
x

array([[1., 6., 2., ..., 2., 2., 3.],
       [6., 3., 4., ..., 4., 3., 5.],
       [4., 4., 4., ..., 3., 3., 4.],
       ...,
       [4., 3., 4., ..., 1., 1., 3.],
       [5., 5., 5., ..., 5., 5., 5.],
       [3., 2., 3., ..., 3., 3., 4.]])

In [48]:
inter

array([0.44353139])

In [49]:
y

array([[3.],
       [6.],
       [4.],
       ...,
       [4.],
       [5.],
       [4.]])

In [65]:
print(sum(abs((np.transpose((np.around(np.dot(coef,np.transpose(x)), 0)))-y)))/len(y))

[0.61219606]


In [91]:
def prediction(question):
    num_question=var_questions.index(question)
    x = np.array(df_questions[var_questions[:num_question]+var_questions[num_question+1:]])
    y = np.array(df_questions[question])
    model_linRegMul = LinearRegression()
    model_linRegMul.fit(x, y)
    coef=model_linRegMul.coef_
    inter=model_linRegMul.intercept_
    print(question, 'erreur=', sum(abs((np.transpose((np.around(np.dot(coef,np.transpose(x)), 0)))-y)))/len(y))
    print(question, 'erreur avec moyenne=', sum(abs(y.mean()-y)/len(y)))

In [89]:
question='Deplacements_enfants_personnes_agees'
num_question=var_questions.index(question)
x = np.array(df_questions[var_questions[:num_question]+var_questions[num_question+1:]])
y = np.array(df_questions[question])
model_linRegMul = LinearRegression()
model_linRegMul.fit(x, y)
coef=model_linRegMul.coef_
inter=model_linRegMul.intercept_
print(coef)
print(question, 'erreur=', sum(abs((np.transpose((np.around(np.dot(coef,np.transpose(x)), 0)))-y)))/len(y))


[ 0.01453226  0.05948252  0.01343629  0.00828165  0.00485627 -0.0062039
  0.05154745  0.01264835  0.00202899  0.01963836  0.01509939 -0.00791622
  0.01612252  0.0834941   0.49479563  0.01161774  0.07054477  0.05402675
 -0.01339003  0.00301531  0.01567229  0.00878521 -0.00651132  0.00961722
  0.00254633  0.0033362  -0.00726798  0.00739317 -0.02028796 -0.01153403
 -0.00906448  0.100517  ]
Deplacements_enfants_personnes_agees erreur= 0.38892664047035186


In [90]:
question='Deplacements_enfants_ecole'
num_question=var_questions.index(question)
x = np.array(df_questions[var_questions[:num_question]+var_questions[num_question+1:]])
y = np.array(df_questions[question])
model_linRegMul = LinearRegression()
model_linRegMul.fit(x, y)
coef=model_linRegMul.coef_
inter=model_linRegMul.intercept_
print(coef)
print(question, 'erreur=', sum(abs((np.transpose((np.around(np.dot(coef,np.transpose(x)), 0)))-y)))/len(y))

[ 1.08248691e-02  4.27641306e-03 -3.27698382e-03  3.45445522e-02
  4.45528768e-02 -9.19187925e-04  7.49930801e-02  3.23885313e-03
  3.06079503e-02  2.51448757e-02  3.41200175e-02 -1.70664609e-02
  7.17170687e-03  7.88203078e-02  5.42445941e-01  3.46662968e-02
  6.43993150e-03  2.15519459e-02 -8.40960629e-04  9.20821072e-03
  6.25219176e-03  1.67675762e-03  2.67723963e-04 -2.51969710e-03
 -2.39103097e-05 -9.04210942e-03  8.80666891e-03  6.29886503e-03
 -2.63503871e-03  2.63347197e-04 -2.51379670e-04  6.34606497e-02]
Deplacements_enfants_ecole erreur= 0.3922061039383106


In [87]:
y

array([[3.],
       [6.],
       [4.],
       ...,
       [4.],
       [5.],
       [4.]])

In [92]:
for i in var_questions:
    prediction(i)

Deplacement_a_pied erreur= 0.6121960587348952
Deplacement_a_pied erreur avec moyenne= 1.074408202524149
Agencement_voirie erreur= 0.5439182202263125
Agencement_voirie erreur avec moyenne= 1.1897045574586114
conflits_pietons erreur= 1.1094336277956687
conflits_pietons erreur avec moyenne= 1.3345392649512167
Conducteurs_respectent erreur= 0.6511655390433421
Conducteurs_respectent erreur avec moyenne= 1.1873785284309
Circulation_vehicules_motorises erreur= 0.8123024197122345
Circulation_vehicules_motorises erreur avec moyenne= 1.0134110882548644
Deplacements_pied_commune erreur= 2.119153839335835
Deplacements_pied_commune erreur avec moyenne= 0.9875987776667166
Marche_securite erreur= 0.3939196974621089
Marche_securite erreur avec moyenne= 0.9912906843917072
Securite_rues_services erreur= 0.5990191154312051
Securite_rues_services erreur avec moyenne= 1.0912013205949929
Securite_rues_residentielles erreur= 0.8181818181818182
Securite_rues_residentielles erreur avec moyenne= 1.0566606627737